world:
  weather:
    cloudiness: 100
    fog_density: 100
    wetness: 5
    precipitation_deposits: 0
    fog_distance: 0
    fog_falloff: 0
    precipitation: 0
    wind_intensity: 0
    sun_altitude_angle: -90
    rayleigh_scattering_scale: 0.02
    scattering_intensity: 1

dataset_config:
  weather: "foggy_night"
  weather_abbreviation: "fn"